const rota = require('express').Router()
const controllerLikes = require("./Controllers/controllerLikes")
const upload = require('./upload')
const controllerUsuario = require('./Controllers/controllerUsuario')
const controllerPost = require('./Controllers/controllerPost')
const controllerComentarios = require('./Controllers/controllerComentario')
rota.post("/upload",upload.single('imagem'),controllerPost.postar)
rota.delete('/delete',upload.single('imagem'),controllerPost.deletar)
rota.post('/jwt',upload.single('imagem'),controllerUsuario.autenticarCliente)
rota.post('/cadastrarUsuario',upload.single('avatar'),controllerUsuario.cadastrarUsuario)
rota.get("/",controllerPost.listar)
rota.get("/getUsuarios",controllerUsuario.exibirCliente)
rota.post("/setLikes",upload.single('avatar'),controllerLikes.setLikes)
rota.get("/getLikes",upload.single('avatar'),controllerLikes.getLikes)
rota.put("/updateLikes",upload.single('avatar'),controllerLikes.updataLikes)
rota.delete("/deleteLikes",upload.single('avatar'),controllerLikes.deleteLike)
rota.post("/getLikePorId",upload.single('avatar'),controllerLikes.getLikesPorId)
rota.post("/postarComentario",upload.single('avatar'),controllerComentarios.postarComentario)
rota.post("/getComentario",upload.single('avatar'),controllerComentarios.getComentarios)
rota.delete("/deleteComentario",upload.single('avatar'),controllerComentarios.deleteComentarios)
module.exports = rota